In [ ]:
# Trần Nguyễn Vĩnh Uy - 20IT502

In [1]:
import numpy as np

In [2]:
print(np.__version__)
print(np.show_config())

1.26.1
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /c/opt/64/include
    lib directory: /c/opt/64/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SKYLAKEX MAX_THREADS=2
    pc file directory: C:/opt/64/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep2300277146320
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.1
Compilers:
  c:
    commands: cl
    linker: link
    name: msvc
    version: 19.29.30152
  c++:
    commands: cl
    linker: link
    name: msvc
    version: 19.29.30152
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.3
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows


In [8]:
arr = np.array([1,2,3,4,5])
print("One-dimesional Numpy array: ", arr)
l = [1,2,3,4]
print("Original List: ", l)
list_arr = np.array(l)
print("One-dimensional NumPy array: ", list_arr)
two_arr = arr = np.array([[1,2,3], [4,5,6]])
listOfLists = [[1,2,3],[4,5,6],[7,8,9]]
print("Original list of lists: ", listOfLists)
list2_arr = np.array(listOfLists)
print("Two diemnsional: ",list2_arr)

One-dimesional Numpy array:  [1 2 3 4 5]
Original List:  [1, 2, 3, 4]
One-dimensional NumPy array:  [1 2 3 4]
Original list of lists:  [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Two diemnsional:  [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
#1.2.2
my_list = [1,2,3,4,5,6,7,8]
print(np.asarray(my_list))
my_tuple = ([8,4,6], [1,2,3])
print(np.asarray(my_tuple))

[1 2 3 4 5 6 7 8]
[[8 4 6]
 [1 2 3]]


In [12]:
#1.2.3
x = np.ones((5,5))
print(x)
x[1:-1, 1:-1] = 0
print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [13]:
x = np.arange(1,10).reshape(3,3)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
x = np.zeros((8,8), dtype= int)
x[1::2, ::2] = 1
x[::2, 1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [16]:
#1.2.7
x = np.zeros(10, dtype = int)
print(x)
print("Update sixth value to 11")
x[6] = 11
print(x)

[0 0 0 0 0 0 0 0 0 0]
Update sixth value to 11
[ 0  0  0  0  0  0 11  0  0  0]


In [17]:
#1.2.8
x = np.empty((5,7))
print(x)
y = np.full((4,3), 9)
print(y)

[[1.28747008e-311 1.28750988e-311 1.69121096e-306 6.23061763e-307
  2.22526399e-307 6.23053614e-307 7.56592338e-307]
 [1.60216183e-306 7.56602523e-307 3.56043054e-307 1.37961641e-306
  2.22518251e-306 1.33511969e-306 6.23037317e-307]
 [6.23053954e-307 9.34609790e-307 8.45593934e-307 9.34600963e-307
  9.34598925e-307 1.42418715e-306 1.95819401e-306]
 [1.37961370e-306 6.23054633e-307 9.34598926e-307 6.89804132e-307
  9.34598926e-307 8.01091099e-307 1.24610927e-306]
 [2.22522597e-306 8.90109671e-307 1.86920872e-306 6.89810244e-307
  1.24611266e-306 2.22522596e-306 2.56765117e-312]]
[[9 9 9]
 [9 9 9]
 [9 9 9]
 [9 9 9]]


In [18]:
#1.2.9
x = np.eye(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
#1.3.1
y = np.array([
    [3,6,9,12],
    [15,18,21,24],
    [27,30,33,36],
    [39,42,45,48],
    [51,54,57,60]
])
y[::2, 1::2]

array([[ 6, 12],
       [30, 36],
       [54, 60]])

In [20]:
a = np.array([3,4,6,10,24,89,45,43,46,99,100])
div3 = a[a%3!=0]
print(div3)
div5 = a[a%5==0]
print(div5)
print(a[(a%3==0) & (a%5==0)])
a[a%3==0] = 42
print(a)

[  4  10  89  43  46 100]
[ 10  45 100]
[45]
[ 42   4  42  10  42  89  42  43  46  42 100]


In [21]:
#1.4.1
p = np.array([[0,0,0],[1,2,3],[4,5,6]])
q = np.array([10,11,12])
print(p)
print(q)
print(p+q)

[[0 0 0]
 [1 2 3]
 [4 5 6]]
[10 11 12]
[[10 11 12]
 [11 13 15]
 [14 16 18]]


In [31]:
#1.4.2
cost = np.array([20,15,25])
print("Pie cost: ", cost)
sales = np.array([[2,3,1], [6,3,3], [5,3,5]])
print("Pie sales:\n", sales)
cost1 = np.repeat(cost, 3).reshape((3,3))
cost1
print(cost1*sales)

Pie cost:  [20 15 25]
Pie sales:
 [[2 3 1]
 [6 3 3]
 [5 3 5]]
[[ 40  60  20]
 [ 90  45  45]
 [125  75 125]]


In [32]:
#1.5.1
arrayA = np.array([[1,2,3,4],[5,6,7,8], [9,10,11,12]])
arrayA

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [39]:
print(np.ndim(arrayA))
print(np.shape(arrayA))
print(np.size(arrayA))
print(arrayA.itemsize)

2
(3, 4)
12
4


In [40]:
#1.6.1
x = np.arange(1,10)
print(x)
print(x[::-1])

[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]


In [41]:
#1.6.2
x = np.arange(1,10)
print(x)
x = np.asfarray(x)
print(x)

[1 2 3 4 5 6 7 8 9]
[1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [44]:
#1.6.3
array1 = np.array([0,1,2,3,5])
print("Array1: ", array1)
array2 = [0,2,4]
print("Array2: ", array2)
print(np.in1d(array1, array2))

Array1:  [0 1 2 3 5]
Array2:  [0, 2, 4]
[ True False  True False False]


In [46]:
#1.6.4
array1= np.array([0,10,20,40,60])
print("Array1: ", array1)
array2 = [10,30,40]
print("Array2: ", array2)
print(np.intersect1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
[10 40]
