In [ ]:
# Trần Nguyễn Vĩnh Uy - 20IT502

In [20]:
# 2.1
import numpy as np
arr1 = np.zeros(5, dtype = int)
print("Array of 5 zeros: ", arr1)
arr2 = np.ones(10, dtype = int)
print("Array of 10 ones: ", arr2)
arr3 = np.full(5, 3.141)
print("Array of 5 3.141: ", arr3)
arr4 = np.arange(1, 21, 1, dtype = int)
print("Array of the integers 1 to 20: ",arr4)
arr5 = np.ones((5,5), dtype = int)
print("5x5 matrix of ones: \n", arr5)

Array of 5 zeros:  [0 0 0 0 0]
Array of 10 ones:  [1 1 1 1 1 1 1 1 1 1]
Array of 5 3.141:  [3.141 3.141 3.141 3.141 3.141]
Array of the integers 1 to 20:  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
5x5 matrix of ones: 
 [[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [21]:
# 2.3
arr = np.linspace(1, 10, 20)
print(arr)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


In [39]:
# 2.4
arr = np.random.random(size=(6,6))
print(arr)
print("Rows 0, 1, 2: \n", arr[:3, :])
print("Rows 0, 1, 5: \n", arr[[0,1,5], :])
print("Columns 0, 1, 2: \n", arr[:, :3])
print("Columns 0, 1, 3: \n", arr[:, [0,1,3]])
print("Columns 0, 1, 2 and Rows 2, 3: \n", arr[2:4, :3])
print("Odd rows and evens column: \n", arr[::2, 1::2])

[[0.05828299 0.01142964 0.75121895 0.50338049 0.74136755 0.77165263]
 [0.95317643 0.6829745  0.1206192  0.99752093 0.90624954 0.82297537]
 [0.7397902  0.12309469 0.48797847 0.55886566 0.748348   0.28554272]
 [0.23430839 0.97506769 0.82179627 0.40645944 0.73073299 0.72088866]
 [0.59167957 0.20223813 0.7465735  0.16102097 0.24120121 0.05411977]
 [0.11409102 0.37546501 0.09515138 0.21772258 0.18898841 0.00193249]]
Rows 0, 1, 2: 
 [[0.05828299 0.01142964 0.75121895 0.50338049 0.74136755 0.77165263]
 [0.95317643 0.6829745  0.1206192  0.99752093 0.90624954 0.82297537]
 [0.7397902  0.12309469 0.48797847 0.55886566 0.748348   0.28554272]]
Rows 0, 1, 5: 
 [[0.05828299 0.01142964 0.75121895 0.50338049 0.74136755 0.77165263]
 [0.95317643 0.6829745  0.1206192  0.99752093 0.90624954 0.82297537]
 [0.11409102 0.37546501 0.09515138 0.21772258 0.18898841 0.00193249]]
Columns 0, 1, 2: 
 [[0.05828299 0.01142964 0.75121895]
 [0.95317643 0.6829745  0.1206192 ]
 [0.7397902  0.12309469 0.48797847]
 [0.234308

In [25]:
# 2.5
arrOnes = np.zeros((5,5))
print("Before: \n", arrOnes)
arrOnes[1:-1, 1:-1] = 1
print("After: \n", arrOnes)

Before: 
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
After: 
 [[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [57]:
# 2.6
a = np.arange(1, 26).reshape(5, -1)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [75]:
a[-2, -1]

20

In [60]:
a[1:, -2:]

array([[ 9, 10],
       [14, 15],
       [19, 20],
       [24, 25]])

In [61]:
a[1]

array([ 6,  7,  8,  9, 10])

In [63]:
a[2:4]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [64]:
a[1:3, 2:4]

array([[ 8,  9],
       [13, 14]])

In [65]:
np.sum(a)

325

In [74]:
for i in a:
    print(np.sum(i))

15
40
65
90
115


In [77]:
a[a > np.mean(a)]

array([14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])

In [89]:
# 2.7
arr1 = np.array([[1, -5, 6, -1, 0],[5, 2, 0, 4, -2],[-7, -7, 1, -8, 4],[-5, 7, 2, -9, 5], [5, 3, 0, 2, 1],
                [0,6,4,0,2]])
print(arr1)
print(arr1.shape)
print(arr1[3, 4])
print(arr1[5, 0])
print(arr1[5, 2])

[[ 1 -5  6 -1  0]
 [ 5  2  0  4 -2]
 [-7 -7  1 -8  4]
 [-5  7  2 -9  5]
 [ 5  3  0  2  1]
 [ 0  6  4  0  2]]
(6, 5)
5
0
4


In [7]:
# 2.8
import numpy as np
np.random.seed(123)
b = np.random.randn(10)
print(np.argmin(b))

6


In [7]:
# 2.9
import numpy as np
n = np.random.rand(10,3)
b = np.abs(n-0.5)
ind = np.argsort(b)
ind2 = ind[:,0]
b2 = n[np.arange(n.shape[0]),ind2]
print(b2)

[0.48613811 0.44173501 0.43282142 0.39867884 0.29046955 0.40902374
 0.50073691 0.8352787  0.34455743 0.5797171 ]


In [8]:
# 2.10
a1 = np.random.rand(3,3)
a2 = np.random.rand(3)
a3 = a1 + a2
print(a3)

[[1.43863548 1.53719013 1.07035605]
 [0.86431698 1.00224532 0.80926504]
 [1.19122247 1.35151277 0.80379977]]


In [13]:
# 2.11
pos = np.array([[1.72, 2.56],
               [0.24, 5.67],
               [-1.24, 5.45],
               [-3.17, -0.23],
               [1.17, -1.23],
               [1.12, 1.08]])
ref = np.array([1.22, 1.18])
newArr = pos-ref
np.sqrt(newArr[::1, 0]**2 + newArr[::1, 1]**2)

array([1.46778745, 4.59570452, 4.9279306 , 4.61087844, 2.41051862,
       0.14142136])

In [27]:
# 2.12
arr1 = np.array([10,20,30])
arr2 = np.array([10,30,30])
a1 = np.where(arr1 == arr2, True, False)
print(a1)

[ True False  True]


In [26]:
# 2.13
arr1 = np.array([10,20,30])
arr2 = np.array([10,30,30])
a1 = np.where(arr1 == arr2)[0]
print(a1)

[0 2]


In [33]:
# 2.14
def clip_values(arr, min_val, max_val):
    newArr = np.clip(arr, min_val, max_val)
    return newArr

arr = np.array([1, 2, 3])
min_val = 2
max_val = 2

newArr = clip_values(input_array, min_val, max_val)
print("Default Array:")
print(arr)
print("Clipped Array:")
print(newArr)

Default Array:
[1 2 3]
Clipped Array:
[2 2 2]


In [34]:
# 2.15
varArr = np.array([
    [2,-2,3],
    [3,3,9],
    [3,3,5]
])
resArr = np.array([-1,0,4])
x = np.linalg.solve(varArr, resArr)
print(x)

[ 2.  1. -1.]


In [37]:
# 2.16
newArr = np.dot(varArr, x) - resArr
newArr

array([0., 0., 0.])